library(dplyr)
setwd("C:/Users/cfgal/OneDrive/Documents/Coursera/Data Science Specialization/Exploratory Data Analysis/Assignment 1")
hpc <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE)
hpc <- subset(hpc, Date == "1/2/2007" | Date == "2/2/2007")
hpc <- mutate(hpc, Date = as.Date(Date, "%d/%m/%Y"))
hpc <- mutate(hpc, Global_active_power = as.numeric(Global_active_power))

hpc <- mutate(hpc, weekday = weekdays(Date))
time <- paste(hpc$Date, hpc$Time)
time <- strptime(time, "%Y-%m-%d %H:%M:%S")
hpc <- cbind(hpc, time)
plot(hpc$time, hpc$Global_active_power, pch = NA, ylab = "Global Active Power (kilowatts)", xlab = "")
lines(hpc$time, hpc$Global_active_power)
dev.copy(png, file = "plot2.png", width = 480, height = 480)
dev.off()